### ISSUE TITLE
Fn + key performs actions

### ISSUE THREAD

**Issue by tejasraman** [wad11656/BrightKeyMap#1]
Hi @wad11656 

I was tired of broken brightness and the ugly boot camp volume dialog, so I started using this on my MacBook Pro (2011). One thing that annoys me is that pressing Fn + the key still performs the action. I know zero AHK scripting so would this be possible?

This was the only software that gave me brightness control with keyboard though. Thanks so much!

**Comment by tejasraman** [comment]
IMHO this was a big enougb issue to stup using Win11 on that Mac (needed F11/F12 to open devtools in edge/firefox).

**Comment by wad11656** [comment]
Yeah this is a problem. I tried multiple times for several hours to get the Fn key to work. But AutoHotKey often can't access the Fn key, apparently because it's often registered on the hardware level instead of the software level. I can probably modify this to use an alternative key (e.g., ctrl or alt key) as the Fn key

**Comment by wad11656** [comment]
Yeah that was a problem. You can try the new version and let me know if it works

**Comment by tejasraman** [comment]
Nice. 👍
